```{r}
source("preprocessing.R")
source("cox_regression.R")
source("gbm_regression.R")
source("aft_regression.R")
source("xgboost_regression.R")
source("concordanceIndex.R")
source("../Classification/classification_models.R")
source("../Classification/model_evaluation_visual.R")
source("compute_IBS.R")
source("../dataPreprocessing.R")
```


```{r}
run_cox = function(indexEvent, outcomeEvent, pcaExplainedVariance = 0.9){
  source("../dataLoader.R")
  outputs <- preprocess(train, test, pcaExplainedVar = pcaExplainedVariance)
  final_train_data = data.frame(outputs[[1]])
  final_test_data = outputs[[2]]
  
  
  cox_list <- cox_regression(final_train_data, final_test_data)
  
  # Extract elements from the cox list
  # Predictions made on testing set of Borrow to Repay
  pred_cox <- cox_list[[1]] 
  # Trained cox model using the training set from Borrow to Repay.
  cox_model <- cox_list[[2]]  
  
  concordance_cox <- concordanceIndex(pred_cox,final_test_data,"cox")
  # Split into 50 time points based on observation time
  times <- seq(
      from = min(final_test_data$timeDiff / 86400),
      to = max(final_test_data$timeDiff / 86400),    
      length.out = 50                            
    )
  
  
  ibs_cox_result <- compute_IBS(
    model = cox_model,
    model_type = "cox",
    train_data = final_train_data,
    test_data = final_test_data,
    times = times,
    status_col = "status",
    time_col = "timeDiff",
    return_brier_scores = TRUE
  )
  
  ibs_cox <- ibs_cox_result$IBS
  brier_scores_cox <- ibs_cox_result$brier_scores
  
  return(list(concordance_cox, ibs_cox))
}
```

```{r}

cox_results <- data.frame()

indexEvents <- list.dirs(path = "../Data/Survival_Data/", full.names = FALSE, recursive=FALSE)
for(indexEvent in indexEvents){
  outcomeEvents = list.dirs(path=paste0("../Data/Survival_Data/", indexEvent), full.names=FALSE, recursive = FALSE)
  for(outcomeEvent in outcomeEvents){
    if(outcomeEvent %in% c("X_test", "X_train")){
      next
    }
    outputs_pca60 <- run_cox(indexEvent, outcomeEvent, pcaExplainedVariance = 0.6)
    outputs_pca70 <- run_cox(indexEvent, outcomeEvent, pcaExplainedVariance = 0.7)
    outputs_pca80 <- run_cox(indexEvent, outcomeEvent, pcaExplainedVariance = 0.8)
    outputs_pca90 <- run_cox(indexEvent, outcomeEvent, pcaExplainedVariance = 0.9)
    outputs_pca95 <- run_cox(indexEvent, outcomeEvent, pcaExplainedVariance = 0.95)
    
    results <- data.frame(
      indexEvent = indexEvent,
      outcomeEvent = outcomeEvent,
      c_index_60 = outputs_pca60[[1]],
      ibs_60 = outputs_pca60[[2]],
      c_index_70 = outputs_pca70[[1]],
      ibs_70 = outputs_pca70[[2]],
      c_index_80 = outputs_pca80[[1]],
      ibs_80 = outputs_pca80[[2]],
      c_index_90 = outputs_pca90[[1]],
      ibs_90 = outputs_pca90[[2]],
      c_index_95 = outputs_pca95[[1]],
      ibs_95 = outputs_pca95[[2]]
    )
    
    cox_results <- cox_results %>%
      bind_rows(results)
    
  }
}

saveRDS(cox_results, file="Results/cox_results.rds")

```


```{r}
source("../Classification/get_classification_cutoff.R")
# Let's try a classification model:
indexEvent = "Deposit"
outcomeEvent = "Account Liquidated"

source("../dataLoader.R")
outputs <- preprocess(train, test, pcaExplainedVar = 0.9, classificationTask = TRUE, get_classification_cutoff(indexEvent, outcomeEvent))

final_train_data <- outputs[[1]]
final_test_data <- outputs[[2]]

lr_results <- logistic_regression(final_train_data, final_test_data)


```