```{r}
library(readr)
library(dplyr)
library(lubridate)

source("../feature_creation.R")

cosmeticsOriginal <- read_rds("/data/IDEA_DeFi_Research/Data/eCommerce/Cosmetics/transactionsOriginal.rds")
electronicsOriginal <- read_rds("/data/IDEA_DeFi_Research/Data/eCommerce/Electronics/transactionsOriginal.rds")
```

```{r}
# The original structure for the Cosmetics transactions has 12 columns:
# time, event_name, product_id, category_id, category_name, brand, price, user_id, session, category_1, category_2, category_3

# Time should be converted to timestamp, using a unix timestamp instead of a date/time
cosmeticsStandardized <- cosmeticsOriginal %>%
  mutate(timestamp = as.numeric(as.POSIXct(time))) %>%
  select(-time)

# event_name is functionally the same as "type", representing what kind of transaction was made:
cosmeticsStandardized <- cosmeticsStandardized %>%
  rename(type = event_name)

# Category_id and category_name are extraneous; they are both an index for the categories, but category_1, category_2, and category_3 provide the same information in a split form:
cosmeticsStandardized <- cosmeticsStandardized %>%
  select(-category_id, -category_name)

# Categories that are Not Defined can be NA:
cosmeticsStandardized <- cosmeticsStandardized %>%
  mutate(category_1 = case_when(category_1 == "Not defined" ~ NA,
                                TRUE ~ category_1),
         category_2 = case_when(category_2 == "Not defined" ~ NA,
                                TRUE ~ category_2),
         category_3 = case_when(category_3 == "Not defined" ~ NA,
                                TRUE ~ category_3))

# price should be renamed 'amount'
cosmeticsStandardized <- cosmeticsStandardized %>%
  rename(amount = price)

# brand can be prefixed with "product" and Not Defined set to NA:
cosmeticsStandardized <- cosmeticsStandardized %>%
  rename(product_brand = brand) %>%
  mutate(product_brand = case_when(product_brand == "Not defined" ~ NA,
                                   TRUE ~ product_brand))

# rename user_id to just user
cosmeticsStandardized <- cosmeticsStandardized %>%
  rename(user = user_id)


# Session is an interesting feature, but it is going to cause some issues when it comes to creating a meaningful vocab.
# I am going to create a replacement feature, newSession, which indicates whether each transaction
# was the first of a new session for a user (TRUE) or a continuation of a prior session (FALSE)
cosmeticsStandardized <- cosmeticsStandardized %>%
  arrange(timestamp) %>%
  group_by(user, session) %>%
  mutate(newSession = row_number() == 1) %>%
  ungroup() %>%
  select(-session)

# We need an id column:
cosmeticsStandardized$id <- 1:nrow(cosmeticsStandardized)

```

```{r}
# Add time features:
cosmeticsStandardized <- create_time_features(cosmeticsStandardized)
# Add cumulative user history:
cosmeticsStandardized <- add_cumulative_user_history(cosmeticsStandardized, skip_amount_types = c(), amount_cols = c("amount"))
```
```{r}
cosmeticsStandardized <- add_windowed_user_history(cosmeticsStandardized)
```

```{r}
# Write the standardized features to disk:
saveRDS(cosmeticsStandardized, file="/data/IDEA_DeFi_Research/Data/eCommerce/Cosmetics/transactions_user_time.rds")
```