
```{r}
save_pheatmap_pdf <- function(x, filename, width=1200, height=1000) {
  pdf(filename, width = width, height = height)
  grid::grid.newpage()
  grid::grid.draw(x$gtable)
  dev.off()
}
```
Load necessary libraries:
```{r}
library(pheatmap)
library(dplyr)
library(xtable)
library(readr)
library(tidyr)
library(tibble)
library(ggpubr)
```

```{r}
pubFontSize = 18
pValSize = 8
pubWidth = 8
pubHeight = 6
pubColorScheme = "Set1"
```


# Read in the prediction results and rename columns to just be model names:
```{r}
benchmark_results <- read_csv("../Results/Survival_Prediction/originalBenchmark/final_results_updated.csv") %>%
  select(-DeepHit, -DeepSurv) %>%
  mutate(features = "benchmark") %>%
  mutate(outcomeEvent = case_when(outcomeEvent == "account liquidated" ~ "liquidated",
                                  TRUE ~ outcomeEvent)) %>%
  mutate(dataset = paste0(indexEvent, "-", outcomeEvent)) %>%
  select(-indexEvent, -outcomeEvent)

benchmark_results <- benchmark_results %>%
  bind_rows(
    benchmark_results %>%
      summarise(
        XGBoost = mean(XGBoost, na.rm = TRUE),
        Cox = mean(Cox, na.rm = TRUE),
        AFT = mean(AFT, na.rm = TRUE),
        RSF = mean(RSF, na.rm = TRUE),
        features = first(features),
        dataset = "mean"
      )
  )

raw_results_original <- read_rds("../Results/Survival_Prediction/raw_seqLen10/results.rds") %>%
  mutate(features = "raw") %>%
  mutate(outcomeEvent = case_when(outcomeEvent == "Account Liquidated" ~ "liquidated",
                                  TRUE ~ tolower(outcomeEvent))) %>%
  mutate(dataset = paste0(tolower(indexEvent), "-", outcomeEvent)) %>%
  select(-indexEvent, -outcomeEvent) %>%
  mutate(model = str_remove(model, "_.*$")) %>%
  pivot_wider(names_from = "model",
              values_from = "c_index") %>%
  select(-Cox)

raw_results <- read_rds("../Results/Survival_Prediction/raw_seqLen10_updated/results_cox.rds") %>%
  select(c_index) %>%
  rename(Cox = c_index)

raw_rsf <- read_rds("../Results/Survival_Prediction/raw_seqLen10_updated/results_rsf.rds") %>%
  select(c_index) %>%
  rename(RSF = c_index)

raw_results <- raw_results_original %>%
  bind_cols(raw_results) %>%
  bind_cols(raw_rsf)

raw_results <- raw_results %>%
  bind_rows(
    raw_results %>%
      summarise(
        XGBoost = mean(XGBoost, na.rm = TRUE),
        Cox = mean(Cox, na.rm = TRUE),
        AFT = mean(AFT, na.rm = TRUE),
        RSF = mean(RSF, na.rm = TRUE),
        features = first(features),
        dataset = "mean"
      )
  )
  
ltm_results <- read_rds("../Results/Survival_Prediction/ltm_small_updated/results.rds") %>%
  mutate(features = "LTM") %>%
  mutate(outcomeEvent = case_when(outcomeEvent == "Account Liquidated" ~ "liquidated",
                                  TRUE ~ tolower(outcomeEvent))) %>%
  mutate(dataset = paste0(tolower(indexEvent), "-", outcomeEvent)) %>%
  select(-indexEvent, -outcomeEvent) %>%
  mutate(model = str_remove(model, "_.*$")) %>%
  pivot_wider(names_from = "model",
              values_from = "c_index")

ltm_rsf <- read_rds("../Results/Survival_Prediction/ltm_small_updated/results_rsf.rds") %>%
  select(c_index) %>%
  rename(RSF = c_index)

ltm_results <- ltm_results %>%
  bind_cols(ltm_rsf)

ltm_results <- ltm_results %>%
  bind_rows(
    ltm_results %>%
      summarise(
        XGBoost = mean(XGBoost, na.rm = TRUE),
        Cox = mean(Cox, na.rm = TRUE),
        AFT = mean(AFT, na.rm = TRUE),
        RSF = mean(RSF, na.rm = TRUE),
        features = first(features),
        dataset = "mean"
      )
  )
```

```{r}
all_results <- bind_rows(benchmark_results, raw_results, ltm_results)

results_long <- all_results %>%
  pivot_longer(
    cols = -c(dataset, features),
    names_to = "model",
    values_to = "c_index"
  )

results_long$model <- factor(results_long$model, levels = c("XGBoost", "AFT", "Cox", "RSF"))
results_long$dataset <- factor(results_long$dataset, levels = c("mean",setdiff(unique(results_long$dataset), "mean")))
# Get the level index of "mean" (assuming factor ordering matches your plot)
mean_index <- which(levels(results_long$dataset) == "mean")

```

```{r}
library(ggplot2)
library(RColorBrewer)

prediction_results <- ggplot(results_long, aes(x = features, y = dataset, fill = c_index)) +
  geom_tile(color = "white") +
  scale_fill_gradientn(colors = colorRampPalette(rev(brewer.pal(9, "RdYlBu")))(100)) +  # you can tune colors
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +  # rotate model names
  facet_wrap(~ model, ncol = 4) +
  geom_hline(yintercept = mean_index+0.5, linewidth = 1, color = "black") +
  labs(
    title = "Survival Prediction Model Performance Across Feature Sets",
    x = "Model",
    y = "Dataset",
    fill = "C-index"
  ) + 
  geom_text(aes(label = sprintf("%.2f", c_index)), size = 3)
ggsave("prediction_results.pdf", plot = prediction_results, width = 10, height = 5)
prediction_results
```





Now do all the same things for the classification results:
```{r}
benchmark_results <- read_csv("../Results/Survival_Classification/originalBenchmark/auc_score.csv") %>%
  select(-DeepHit, -DeepLearningClassifier) %>%
  mutate(features = "benchmark") %>%
  rename(dataset = auc_score) %>%
  mutate(dataset = str_replace(dataset, "account liquidated", "liquidated")) %>%
  rename(LogReg = Logistic.Regression,
         DecisionTree = Decision.Tree,
         ElasticNet = Elastic.Net)

benchmark_results <- benchmark_results %>%
  bind_rows(
    benchmark_results %>%
      summarise(
        XGBoost = mean(XGBoost, na.rm = TRUE),
        DecisionTree = mean(DecisionTree, na.rm = TRUE),
        LogReg = mean(LogReg, na.rm = TRUE),
        features = first(features),
        dataset = "mean"
      )
  )

raw_results <- read_rds("../Results/Survival_Classification/raw_seqLen10/results.rds") %>%
  mutate(features = "raw") %>%
  mutate(outcomeEvent = case_when(outcomeEvent == "Account Liquidated" ~ "liquidated",
                                  TRUE ~ tolower(outcomeEvent))) %>%
  mutate(dataset = paste0(tolower(indexEvent), " + ", outcomeEvent)) %>%
  select(-indexEvent, -outcomeEvent, -smote) %>%
  mutate(model = str_remove(model, "_.*$")) %>%
  pivot_wider(names_from = "model",
              values_from = "auc")

raw_results <- raw_results %>%
  bind_rows(
    raw_results %>%
      summarise(
        XGBoost = mean(XGBoost, na.rm = TRUE),
        DecisionTree = mean(DecisionTree, na.rm = TRUE),
        LogReg = mean(LogReg, na.rm = TRUE),
        features = first(features),
        dataset = "mean"
      )
  )
  
ltm_results <- read_rds("../Results/Survival_Classification/ltm_seqLen10/lr_dt_en_results_ltm_small.rds") %>%
  bind_rows(read_rds("../Results/Survival_Classification/ltm_seqLen10/resultsXGB_ltm_small.rds")) %>%
  mutate(features = "LTM") %>%
  mutate(outcomeEvent = case_when(outcomeEvent == "Account Liquidated" ~ "liquidated",
                                  TRUE ~ tolower(outcomeEvent))) %>%
  mutate(dataset = paste0(tolower(indexEvent), " + ", outcomeEvent)) %>%
  select(-indexEvent, -outcomeEvent, -smote, -f1) %>%
  mutate(auc = as.numeric(auc)) %>%
  mutate(model = str_remove(model, "_.*$")) %>%
  pivot_wider(names_from = "model",
              values_from = "auc") 

ltm_results <- ltm_results %>%
  bind_rows(
    ltm_results %>%
      summarise(
        XGBoost = mean(XGBoost, na.rm = TRUE),
        DecisionTree = mean(DecisionTree, na.rm = TRUE),
        LogReg = mean(LogReg, na.rm = TRUE),
        features = first(features),
        dataset = "mean"
      )
  )
```


```{r}
all_results <- bind_rows(benchmark_results, raw_results, ltm_results)
all_results <- all_results %>%
  select(-ElasticNet)

results_long <- all_results %>%
  pivot_longer(
    cols = -c(dataset, features),
    names_to = "model",
    values_to = "auc"
  )


results_long$model <- factor(results_long$model, levels = c("XGBoost", "LogReg", "DecisionTree"))
results_long$dataset <- factor(results_long$dataset, levels = c("mean",setdiff(unique(results_long$dataset), "mean")))
# Get the level index of "mean" (assuming factor ordering matches your plot)
mean_index <- which(levels(results_long$dataset) == "mean")
```



```{r}
library(ggplot2)
library(RColorBrewer)

classification_results <- ggplot(results_long, aes(x = features, y = dataset, fill = auc)) +
  geom_tile(color = "white") +
  scale_fill_gradientn(colors = colorRampPalette(rev(brewer.pal(9, "RdYlBu")))(100)) +  # you can tune colors
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +  # rotate model names
  facet_wrap(~ model) +
  geom_hline(yintercept = mean_index+0.5, linewidth = 1, color = "black") +
  labs(
    title = "Classification Model Performance Across Feature Sets",
    x = "Model",
    y = "Dataset",
    fill = "AUC"
  ) + 
  geom_text(aes(label = sprintf("%.2f", auc)), size = 3)

ggsave("classification_results.pdf", plot = classification_results, width = 7, height = 5)
classification_results
```
